version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    labels:
      - "dependencies"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    labels:
      - "dependencies"
    groups:
      dev-dependencies:
        dependency-type: "development"

  - package-ecosystem: "pip"
    directory: "/sdk-python"
    schedule:
      interval: "weekly"
      day: "monday"
    labels:
      - "dependencies"

  - package-ecosystem: "gomod"
    directory: "/sdk-go"
    schedule:
      interval: "weekly"
      day: "monday"
    labels:
      - "dependencies"
