import { writeFileSync } from "node:fs";
import { Command, Errors, Flags } from "@oclif/core";
import type { Domain, ListDomainsResponse } from "@primitivedotdev/api-core";
import { listDomains } from "@primitivedotdev/api-core";
import { createAuthenticatedCliApiClient } from "../api-client.js";
import {
  extractErrorPayload,
  runWithTiming,
  surfaceUnauthorizedHint,
  TIME_FLAG_DESCRIPTION,
  writeErrorWithHints,
} from "../api-command.js";

export function zoneFileUrl(
  baseUrl: string,
  domainId: string,
  outboundOnly: boolean,
): string {
  const url = new URL(
    `${baseUrl.replace(/\/$/, "")}/domains/${encodeURIComponent(domainId)}/zone-file`,
  );
  if (outboundOnly) url.searchParams.set("outbound_only", "true");
  return url.toString();
}

export function contentDispositionFilename(
  value: string | null,
): string | null {
  if (!value) return null;
  const match = /filename\*=UTF-8''([^;]+)|filename="?([^";]+)"?/i.exec(value);
  const raw = match?.[1] ?? match?.[2];
  if (!raw) return null;
  try {
    return decodeURIComponent(raw);
  } catch {
    return raw;
  }
}

function findDomain(domains: Domain[], domain: string): Domain {
  const match = domains.find((entry) => entry.domain === domain);
  if (!match) {
    throw new Errors.CLIError(`Domain ${domain} was not found.`, { exit: 1 });
  }
  return match;
}

async function responseErrorPayload(response: Response): Promise<unknown> {
  const contentType = response.headers.get("content-type")?.toLowerCase() ?? "";
  if (contentType.includes("application/json")) {
    return response.json().catch(() => ({
      code: "http_error",
      message: `HTTP ${response.status} ${response.statusText}`.trim(),
    }));
  }
  const text = await response.text().catch(() => "");
  return {
    code: "http_error",
    message:
      text.trim() || `HTTP ${response.status} ${response.statusText}`.trim(),
  };
}

class DomainsZoneFileCommand extends Command {
  static description = `Download a BIND-format DNS zone file for a domain claim.

  Use this when a DNS provider supports zone-file import and you want to publish all required records at once instead of copying each record manually. The file is generated by the Primitive API, matching the dashboard download flow.

  Agents: after claiming a domain, tell users they can run \`primitive domains zone-file --id <domain-id> --output <domain>.zone\` to get an importable DNS zone file.`;

  static summary = "Download a DNS zone file for a domain";

  static examples = [
    "<%= config.bin %> domains zone-file --id <domain-id>",
    "<%= config.bin %> domains zone-file --id <domain-id> --output example.com.zone",
    "<%= config.bin %> domains zone-file --domain example.com --output example.com.zone",
    "<%= config.bin %> domains zone-file --id <domain-id> --outbound-only",
  ];

  static flags = {
    "api-key": Flags.string({
      description:
        "Primitive API key override (defaults to PRIMITIVE_API_KEY or saved OAuth login credentials)",
      env: "PRIMITIVE_API_KEY",
    }),
    "api-base-url-1": Flags.string({
      description:
        "Override the primary API base URL. Internal testing only; not documented to customers.",
      env: "PRIMITIVE_API_BASE_URL_1",
      hidden: true,
    }),
    "api-base-url-2": Flags.string({
      description:
        "Override the attachments-supporting send host base URL. Internal testing only; not documented to customers.",
      env: "PRIMITIVE_API_BASE_URL_2",
      hidden: true,
    }),
    domain: Flags.string({
      description:
        "Domain name to look up before downloading its zone file. Prefer --id when you have the domain id from `primitive domains add`.",
    }),
    id: Flags.string({
      description:
        "Domain id returned by `primitive domains add` or `primitive domains list`.",
    }),
    output: Flags.string({
      char: "o",
      description:
        "Write the zone file to this path instead of stdout. Defaults to stdout.",
    }),
    "outbound-only": Flags.boolean({
      description:
        "Include only outbound DNS records. Verified domains default to outbound-only at the API; this flag is explicit for agents and scripts.",
    }),
    time: Flags.boolean({
      description: TIME_FLAG_DESCRIPTION,
    }),
  };

  async run(): Promise<void> {
    const { flags } = await this.parse(DomainsZoneFileCommand);

    if (flags.id && flags.domain) {
      throw new Errors.CLIError("Use only one of --id or --domain.", {
        exit: 1,
      });
    }
    if (!flags.id && !flags.domain) {
      throw new Errors.CLIError("Pass --id <domain-id> or --domain <domain>.", {
        exit: 1,
      });
    }

    await runWithTiming(flags.time, async () => {
      const { apiClient, auth, baseUrlOverridden, requestConfig } =
        await createAuthenticatedCliApiClient({
          apiKey: flags["api-key"],
          apiBaseUrl1: flags["api-base-url-1"],
          apiBaseUrl2: flags["api-base-url-2"],
          configDir: this.config.configDir,
        });

      let domainId = flags.id;
      if (!domainId && flags.domain) {
        const result = await listDomains({
          client: apiClient.client,
          responseStyle: "fields",
        });

        if (result.error) {
          const errorPayload = extractErrorPayload(result.error);
          writeErrorWithHints(errorPayload);
          surfaceUnauthorizedHint({
            auth,
            baseUrlOverridden,
            configDir: this.config.configDir,
            payload: errorPayload,
          });
          process.exitCode = 1;
          return;
        }

        const envelope = result.data as ListDomainsResponse | undefined;
        domainId = findDomain(envelope?.data ?? [], flags.domain).id;
      }

      if (!domainId) {
        throw new Errors.CLIError("Could not resolve a domain id.", {
          exit: 1,
        });
      }

      let response: Response;
      try {
        response = await fetch(
          zoneFileUrl(
            requestConfig.resolvedApiBaseUrl1,
            domainId,
            flags["outbound-only"],
          ),
          {
            headers: {
              ...(requestConfig.headers ?? {}),
              ...(auth.apiKey
                ? { authorization: `Bearer ${auth.apiKey}` }
                : {}),
            },
          },
        );
      } catch (error) {
        writeErrorWithHints(error);
        process.exitCode = 1;
        return;
      }

      if (!response.ok) {
        const errorPayload = extractErrorPayload(
          await responseErrorPayload(response),
        );
        writeErrorWithHints(errorPayload);
        surfaceUnauthorizedHint({
          auth,
          baseUrlOverridden,
          configDir: this.config.configDir,
          payload: errorPayload,
        });
        process.exitCode = 1;
        return;
      }

      const zoneFile = await response.text();
      const output = flags.output;
      if (output) {
        writeFileSync(output, zoneFile, "utf8");
        const filename = contentDispositionFilename(
          response.headers.get("content-disposition"),
        );
        process.stderr.write(`Wrote ${filename ?? "zone file"} to ${output}\n`);
        return;
      }
      process.stdout.write(zoneFile);
    });
  }
}

export default DomainsZoneFileCommand;
