export interface FunctionTemplateAuthor {
  id: string;
  name: string;
  url?: string;
}

export interface FunctionTemplateFile {
  relativePath: string;
  contents: string;
}

export interface FunctionTemplateRenderParams {
  name: string;
}

export interface FunctionTemplate {
  id: string;
  title: string;
  summary: string;
  description: string;
  author: FunctionTemplateAuthor;
  tags: string[];
  dependencies: string[];
  devDependencies: string[];
  secrets: string[];
  files: (params: FunctionTemplateRenderParams) => FunctionTemplateFile[];
}

export interface FunctionTemplateSummary {
  id: string;
  title: string;
  summary: string;
  description: string;
  author: FunctionTemplateAuthor;
  tags: string[];
  dependencies: string[];
  devDependencies: string[];
  secrets: string[];
}

export const DEFAULT_FUNCTION_TEMPLATE_ID = "email-reply";

export const PRIMITIVE_TEAM_AUTHOR: FunctionTemplateAuthor = {
  id: "primitive-team",
  name: "Primitive Team",
  url: "https://primitive.dev",
};

// The SDK version range that ships in the scaffolded package.json's
// dependencies. Pinned to the current shipped minor with a caret so
// patch releases of the SDK pick up automatically. Update alongside
// any minor or major version bump of the SDK; keep in lockstep with
// the CLI's own @primitivedotdev/sdk dep range in cli-node/package.json
// so scaffolded projects use the same SDK version the CLI was built
// and tested against.
const SDK_VERSION_RANGE = "^0.28.0";

// The CLI version range that ships in the scaffolded devDependencies.
// Pinned separately from SDK_VERSION_RANGE because @primitivedotdev/cli
// and @primitivedotdev/sdk are independent packages on independent
// release cadences. Coupling them silently breaks `npm install` in
// every scaffolded project the day we bump one without publishing the
// other. Must include this CLI's own version: a `primitive
// functions:init` run from CLI v1.2.3 should scaffold a project that
// resolves at least v1.2.3, so the user does not silently downgrade
// the bin under themselves. The lockstep test in functions-init.test.ts
// enforces that invariant.
const CLI_VERSION_RANGE = "^0.28.0";

// esbuild version range. Pinned to the latest stable major used
// elsewhere in the Primitive codebase for bundling Workers-style
// handlers. Caret range so patch fixes flow in automatically.
const ESBUILD_VERSION_RANGE = "^0.27.0";

// File contents for the scaffolded project. Each renderer takes the
// function name and returns the raw file body. Kept as named exports
// so the unit test can assert content without having to spin up the
// oclif command lifecycle.

export function renderHandler(): string {
  return `// env.PRIMITIVE_API_KEY is auto-injected by the Primitive Functions runtime.
//
// Imports are taken from the \`/api\` subpath, NOT the package root.
// The root export pulls in webhook signing helpers that depend on
// \`node:crypto\`, which breaks Workers-style bundles. The \`/api\`
// subpath is Workers-safe and exposes everything a handler needs.
import {
  createPrimitiveClient,
  normalizeReceivedEmail,
  type EmailReceivedEvent,
} from "@primitivedotdev/sdk/api";

// Loop-protection knob. Only used by the isLoop helper below; the
// handler's outbound reply address is server-defaulted (no
// from-address parameter is passed to client.reply). Update this if
// you later switch to sending from a non-managed-domain address so
// the loop guard recognizes mail returning to it as self-traffic.
const REPLY_FROM = "you@your-domain.primitive.email";

// Loop protection. A deployed Function receives catch-all inbound for
// the managed *.primitive.email subdomain, which includes bounces and
// auto-replies generated by its own outbound traffic. Without this
// guard the handler can respond to its own bounces and create a
// fan-out loop.
//
// The default check returns true when From is on any *.primitive.email
// address (covers the managed subdomain catch-all, the simple
// self-reply case, and bounces from mailer-daemon@*.primitive.email)
// or when From contains REPLY_FROM as a case-insensitive substring.
// Substring matching is deliberate so display-name forms like
// "Support <support@example.com>" match a bare-address REPLY_FROM,
// but it also accepts false positives where REPLY_FROM is a suffix
// of another address (e.g. REPLY_FROM="info@x.com" matches
// "mr.info@x.com"). For strict equality, parse the address out of the
// header and exact-match against REPLY_FROM.
//
// Extend this helper if you need stricter detection. Common additions:
//   - Match the org's signup / account-owner email (not auto-injected
//     into env today; either bake it into a SIGNUP_EMAIL const or read
//     it from a secret you set via \`primitive functions:set-secret\`).
//   - Honor RFC 3834 auto-response headers: skip when
//     \`event.email.headers["auto-submitted"]\` is anything other than
//     "no", or when a \`List-Unsubscribe\` / \`Precedence: bulk\` header
//     is present.
//   - Track Message-ID / In-Reply-To chains to break ping-pong loops
//     between two cooperating handlers on different domains.
export function isLoop(event: EmailReceivedEvent): boolean {
  // event.email.headers.from is the raw RFC 2822 header value, so it
  // may be a bare address ("alice@example.com") or a display-name form
  // ("Alice <alice@example.com>"). Lowercase substring checks match
  // both shapes without needing to parse the bracketed address.
  const from = event.email.headers.from?.toLowerCase() ?? "";
  if (!from) return false;
  if (from.includes(".primitive.email")) return true;
  if (from.includes(REPLY_FROM.toLowerCase())) return true;
  return false;
}

export default {
  async fetch(
    req: Request,
    env: { PRIMITIVE_API_KEY: string },
  ): Promise<Response> {
    try {
      const event = (await req.json()) as EmailReceivedEvent;

      // Only "email.received" exists today. Future event types will
      // arrive with a different discriminator; return 2xx so the
      // delivery loop does not burn its retry budget on payloads you
      // intentionally skipped.
      if (event.event !== "email.received") {
        return Response.json({ ok: true, skipped: event.event });
      }

      // Loop protection runs immediately after the event-type check
      // (the gateway has already HMAC-verified the request before it
      // reaches this handler). See isLoop above for what's covered and
      // how to extend it.
      if (isLoop(event)) {
        return Response.json({ ok: true, skipped: "loop" });
      }

      const client = createPrimitiveClient({ apiKey: env.PRIMITIVE_API_KEY });

      // Recipient gate
      // https://www.primitive.dev/docs/sending#who-you-can-send-to
      // Even via client.reply, sends to the original sender are
      // subject to the recipient gate. New accounts can send to
      // *.primitive.email addresses, verified domains, addresses that
      // have authenticated to you, and other org-member signup emails.
      // Sends to arbitrary external addresses return 403
      // recipient_not_allowed with a structured gates[] array until
      // the recipient has authenticated to you or support has enabled
      // the gate.

      // Recipient routing: a single function can handle multiple inbound
      // addresses by branching on event.email.headers.to. For example,
      // route "support@" to a ticketing flow and "sales@" to a lead
      // capture flow before calling client.reply.

      // client.reply routes through POST /api/v1/emails/{id}/reply
      // (NOT /send-mail) so the server derives recipients, the
      // \`Re: <parent>\` subject, threading headers, and the
      // in_reply_to_email_id foreign key automatically. The FK is
      // what populates the inbound's \`replies\` array on
      // GET /emails/{id}; without it, \`primitive functions:test-function
      // --show-sends\` would report no outbound emails for this handler
      // because the join would miss. Use client.send only when you
      // need to send to a different address than the inbound sender,
      // and pass \`in_reply_to\` explicitly to preserve correlation.
      const reply = await client.reply(normalizeReceivedEmail(event), {
        text: "Got your message.",
      });

      return Response.json({ ok: true, reply });
    } catch (err) {
      // Return 2xx so the webhook delivery loop does not retry a bug
      // it cannot fix. The function-invocation row still records the
      // error body for debugging. Flip to a 5xx status if you want
      // transient failures retried (e.g. a flaky external API you call).
      console.error("handler error:", err);
      return Response.json(
        { ok: false, error: err instanceof Error ? err.message : String(err) },
        { status: 200 },
      );
    }
  },
};
`;
}

export function renderPackageJson(name: string): string {
  const pkg = {
    name,
    version: "0.1.0",
    private: true,
    type: "module",
    scripts: {
      build: "node build.mjs",
      deploy: `npm run build && primitive functions deploy --name ${name} --file ./dist/handler.js`,
      redeploy:
        "npm run build && primitive functions redeploy --id $PRIMITIVE_FUNCTION_ID --file ./dist/handler.js",
    },
    dependencies: {
      "@primitivedotdev/sdk": SDK_VERSION_RANGE,
    },
    devDependencies: {
      // @primitivedotdev/cli ships the primitive bin. Including it as
      // a devDep here means `node_modules/.bin/primitive` resolves to
      // the real CLI inside the scaffolded project so `npm run deploy`
      // works without a global install. Pinned via CLI_VERSION_RANGE,
      // a dedicated constant so the version is decoupled from the SDK
      // range and bumps are explicit on both ends.
      "@primitivedotdev/cli": CLI_VERSION_RANGE,
      esbuild: ESBUILD_VERSION_RANGE,
      typescript: "^5.7.2",
    },
  };
  return `${JSON.stringify(pkg, null, 2)}\n`;
}

export function renderBuildMjs(): string {
  return `import { build } from "esbuild";

// Bundle handler.ts into a single ESM file suitable for the Primitive
// Functions runtime. The runtime is a Workers-style environment, so
// we pick the "worker" / "browser" export conditions on @primitivedotdev/sdk
// (which routes us to the /api subpath safely without dragging in
// node:crypto-dependent webhook helpers).

await build({
  entryPoints: ["handler.ts"],
  bundle: true,
  format: "esm",
  platform: "browser",
  target: "es2022",
  conditions: ["worker", "browser"],
  outfile: "dist/handler.js",
});
`;
}

export function renderTsconfig(): string {
  const tsconfig = {
    compilerOptions: {
      target: "ES2022",
      module: "ESNext",
      moduleResolution: "Bundler",
      strict: true,
      lib: ["ES2022", "WebWorker"],
      types: [],
      esModuleInterop: true,
      skipLibCheck: true,
    },
    include: ["handler.ts"],
  };
  return `${JSON.stringify(tsconfig, null, 2)}\n`;
}

export function renderGitignore(): string {
  return "node_modules\ndist\n";
}

export function renderReadme(name: string): string {
  return `# ${name}

## What this is

A Primitive Function: a JavaScript handler that runs on inbound mail.
It receives the \`email.received\` event, demonstrates a basic reply
via the Primitive SDK, and returns a JSON envelope.

## Develop

\`\`\`
npm install
npm run build
\`\`\`

## Deploy

\`\`\`
npm run deploy
\`\`\`

The deploy step calls \`primitive functions deploy\` (provided by the
\`@primitivedotdev/cli\` package; install with
\`npm install -g @primitivedotdev/cli\` or run via
\`npx @primitivedotdev/cli@latest <command>\`). It requires
\`PRIMITIVE_API_KEY\` to be set in your shell (or pass \`--api-key\`).
Run \`primitive login\` once to save a key in your CLI config if you
prefer that to an env var.
`;
}

function renderEmailReplyTemplateFiles(name: string): FunctionTemplateFile[] {
  return [
    { contents: renderHandler(), relativePath: "handler.ts" },
    { contents: renderPackageJson(name), relativePath: "package.json" },
    { contents: renderBuildMjs(), relativePath: "build.mjs" },
    { contents: renderTsconfig(), relativePath: "tsconfig.json" },
    { contents: renderGitignore(), relativePath: ".gitignore" },
    { contents: renderReadme(name), relativePath: "README.md" },
  ];
}

export const FUNCTION_TEMPLATES: FunctionTemplate[] = [
  {
    author: PRIMITIVE_TEAM_AUTHOR,
    dependencies: ["@primitivedotdev/sdk"],
    description:
      "A deployable TypeScript email handler that validates email.received events, skips likely loops, and replies with the Primitive SDK.",
    devDependencies: ["@primitivedotdev/cli", "esbuild", "typescript"],
    files: ({ name }) => renderEmailReplyTemplateFiles(name),
    id: DEFAULT_FUNCTION_TEMPLATE_ID,
    secrets: [],
    summary: "Reply to inbound email with the Primitive SDK.",
    tags: ["email", "reply", "typescript", "worker"],
    title: "Email Reply",
  },
];

export function functionTemplateIds(
  templates: readonly FunctionTemplate[],
): string[] {
  return templates.map((template) => template.id);
}

export function findFunctionTemplate(
  templates: readonly FunctionTemplate[],
  id: string,
): FunctionTemplate | null {
  return templates.find((template) => template.id === id) ?? null;
}

export function serializeFunctionTemplate(
  template: FunctionTemplate,
): FunctionTemplateSummary {
  return {
    author: { ...template.author },
    dependencies: [...template.dependencies],
    description: template.description,
    devDependencies: [...template.devDependencies],
    id: template.id,
    secrets: [...template.secrets],
    summary: template.summary,
    tags: [...template.tags],
    title: template.title,
  };
}

export function formatFunctionTemplateList(
  templates: readonly FunctionTemplate[],
): string {
  const lines = ["Available Primitive Function templates:", ""];

  for (const template of templates) {
    lines.push(`${template.id}`);
    lines.push(`  title: ${template.title}`);
    lines.push(`  author: ${template.author.name}`);
    lines.push(`  summary: ${template.summary}`);
    lines.push(
      `  tags: ${template.tags.length > 0 ? template.tags.join(", ") : "none"}`,
    );
    lines.push(
      `  secrets: ${
        template.secrets.length > 0 ? template.secrets.join(", ") : "none"
      }`,
    );
    lines.push("");
  }

  lines.push("Use `primitive functions init <name> --template <id>`.");
  return lines.join("\n");
}
