/**
 * Emit a loud stderr banner when a send-mail response indicates the
 * server replayed a cached row instead of putting a fresh message on
 * the wire.
 *
 * Why this exists. The send-mail API auto-derives an idempotency key
 * from the message content (from + to + subject + body). When the
 * same content is sent twice within the server's idempotency window,
 * the second call returns the persisted row from the first call with
 * `idempotent_replay: true` and the original delivery state. No SMTP
 * traffic, no new email lands in the recipient's inbox.
 *
 * Without this banner the JSON response looks indistinguishable from
 * a successful fresh delivery (same `status: "delivered"`, same
 * `id`, same SMTP fields once the row-column-carry-through is in
 * place). A customer debugging "why didn't my second email arrive"
 * has no signal that the second call was a no-op. This banner makes
 * that condition impossible to miss in an interactive shell while
 * leaving stdout JSON output unchanged for scripted consumers.
 *
 * Design:
 * - Writes to stderr only. Stdout JSON is byte-identical to a
 *   non-replay response so `... | jq ...` pipelines keep working.
 * - Pure of side effects beyond the supplied write target so the
 *   unit test can capture writes without mocking `process.stderr`.
 * - Idempotent: safe to call regardless of whether the response
 *   actually carries `idempotent_replay`. Non-replay responses
 *   produce no output.
 */

interface ReplayBannerOptions {
  /** Sink for the banner. Defaults at the call site to `process.stderr`. */
  write: (chunk: string) => void;
}

interface ReplayProbe {
  idempotent_replay?: unknown;
  id?: unknown;
  status?: unknown;
  delivery_status?: unknown;
}

/**
 * If `data` carries `idempotent_replay: true`, write a multi-line
 * stderr banner explaining the replay condition and what the caller
 * can do to bypass it. Otherwise no-op.
 */
export function writeIdempotentReplayBannerIfReplay(
  data: unknown,
  options: ReplayBannerOptions,
): void {
  if (!isReplay(data)) return;

  const probe = data as ReplayProbe;
  const rowId = typeof probe.id === "string" ? probe.id : null;
  const status = typeof probe.status === "string" ? probe.status : null;
  const deliveryStatus =
    typeof probe.delivery_status === "string" ? probe.delivery_status : null;

  const lines: string[] = [
    "note: idempotent replay. this exact send already happened earlier.",
    "      no new MX traffic was generated by this call. nothing new will arrive in any inbox.",
  ];
  if (rowId) lines.push(`      cached row id: ${rowId}`);
  if (status || deliveryStatus) {
    const parts = [
      status ? `status=${status}` : null,
      deliveryStatus && deliveryStatus !== status
        ? `delivery_status=${deliveryStatus}`
        : null,
    ].filter((part): part is string => part !== null);
    if (parts.length > 0) lines.push(`      original ${parts.join(", ")}`);
  }
  lines.push(
    "      to send a fresh copy: vary any field (subject, body, etc.) or",
    "      pass a unique Idempotency-Key on the underlying API call.",
  );

  options.write(`${lines.join("\n")}\n`);
}

function isReplay(data: unknown): boolean {
  if (data === null || typeof data !== "object") return false;
  const probe = data as ReplayProbe;
  return probe.idempotent_replay === true;
}
