// Code generated by ogen, DO NOT EDIT.
package api

type AddDomainRes interface {
	addDomainRes()
}

type CliLogoutRes interface {
	cliLogoutRes()
}

type CreateEndpointRes interface {
	createEndpointRes()
}

type CreateFilterRes interface {
	createFilterRes()
}

type CreateFunctionRes interface {
	createFunctionRes()
}

type CreateFunctionSecretRes interface {
	createFunctionSecretRes()
}

type DeleteDomainRes interface {
	deleteDomainRes()
}

type DeleteEmailRes interface {
	deleteEmailRes()
}

type DeleteEndpointRes interface {
	deleteEndpointRes()
}

type DeleteFilterRes interface {
	deleteFilterRes()
}

type DeleteFunctionRes interface {
	deleteFunctionRes()
}

type DeleteFunctionSecretRes interface {
	deleteFunctionSecretRes()
}

type DiscardEmailContentRes interface {
	discardEmailContentRes()
}

type DownloadAttachmentsRes interface {
	downloadAttachmentsRes()
}

type DownloadDomainZoneFileRes interface {
	downloadDomainZoneFileRes()
}

type DownloadRawEmailRes interface {
	downloadRawEmailRes()
}

type GetAccountRes interface {
	getAccountRes()
}

type GetConversationRes interface {
	getConversationRes()
}

type GetEmailRes interface {
	getEmailRes()
}

type GetFunctionRes interface {
	getFunctionRes()
}

type GetFunctionTestRunTraceRes interface {
	getFunctionTestRunTraceRes()
}

type GetInboxStatusRes interface {
	getInboxStatusRes()
}

type GetSendPermissionsRes interface {
	getSendPermissionsRes()
}

type GetSentEmailRes interface {
	getSentEmailRes()
}

type GetStorageStatsRes interface {
	getStorageStatsRes()
}

type GetThreadRes interface {
	getThreadRes()
}

type GetWebhookSecretRes interface {
	getWebhookSecretRes()
}

type ListDeliveriesRes interface {
	listDeliveriesRes()
}

type ListDomainsRes interface {
	listDomainsRes()
}

type ListEmailsRes interface {
	listEmailsRes()
}

type ListEndpointsRes interface {
	listEndpointsRes()
}

type ListFiltersRes interface {
	listFiltersRes()
}

type ListFunctionLogsRes interface {
	listFunctionLogsRes()
}

type ListFunctionSecretsRes interface {
	listFunctionSecretsRes()
}

type ListFunctionsRes interface {
	listFunctionsRes()
}

type ListSentEmailsRes interface {
	listSentEmailsRes()
}

type PollCliLoginRes interface {
	pollCliLoginRes()
}

type ReplayDeliveryRes interface {
	replayDeliveryRes()
}

type ReplayEmailWebhooksRes interface {
	replayEmailWebhooksRes()
}

type ReplyToEmailRes interface {
	replyToEmailRes()
}

type ResendAgentSignupVerificationRes interface {
	resendAgentSignupVerificationRes()
}

type ResendCliSignupVerificationRes interface {
	resendCliSignupVerificationRes()
}

type RotateWebhookSecretRes interface {
	rotateWebhookSecretRes()
}

type SearchEmailsRes interface {
	searchEmailsRes()
}

type SendEmailRes interface {
	sendEmailRes()
}

type SetFunctionSecretRes interface {
	setFunctionSecretRes()
}

type StartAgentSignupRes interface {
	startAgentSignupRes()
}

type StartCliLoginRes interface {
	startCliLoginRes()
}

type StartCliSignupRes interface {
	startCliSignupRes()
}

type TestEndpointRes interface {
	testEndpointRes()
}

type TestFunctionRes interface {
	testFunctionRes()
}

type UpdateAccountRes interface {
	updateAccountRes()
}

type UpdateDomainRes interface {
	updateDomainRes()
}

type UpdateEndpointRes interface {
	updateEndpointRes()
}

type UpdateFilterRes interface {
	updateFilterRes()
}

type UpdateFunctionRes interface {
	updateFunctionRes()
}

type VerifyAgentSignupRes interface {
	verifyAgentSignupRes()
}

type VerifyCliSignupRes interface {
	verifyCliSignupRes()
}

type VerifyDomainRes interface {
	verifyDomainRes()
}
