// Code generated by ogen, DO NOT EDIT.

package api

// setDefaults set default value of fields.
func (s *CreateEndpointInput) setDefaults() {
	{
		val := CreateEndpointInputKind("http")
		s.Kind.SetTo(val)
	}
	{
		val := bool(true)
		s.Enabled.SetTo(val)
	}
	{
		val := bool(false)
		s.IsRouteTarget.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *CreateWakeScheduleInput) setDefaults() {
	{
		val := string("UTC")
		s.Timezone.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *SemanticSearchInput) setDefaults() {
	{
		val := SemanticSearchInputMode("hybrid")
		s.Mode.SetTo(val)
	}
	{
		val := int(10)
		s.Limit.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *TemplateInstall) setDefaults() {
	{
		val := string("")
		s.Reason = val
	}
}

// setDefaults set default value of fields.
func (s *TemplateSecret) setDefaults() {
	{
		val := bool(true)
		s.Required = val
	}
}

// setDefaults set default value of fields.
func (s *TemplateSecretGroup) setDefaults() {
	{
		val := int(1)
		s.Min = val
	}
}

// setDefaults set default value of fields.
func (s *TemplateSource0) setDefaults() {
	{
		val := string(".")
		s.Dir = val
	}
}

// setDefaults set default value of fields.
func (s *TemplateVariable) setDefaults() {
	{
		val := TemplateVariableType("string")
		s.Type = val
	}
}
