// Code generated by ogen, DO NOT EDIT.
package api

type AddDomainRes interface {
	addDomainRes()
}

type CliLogoutRes interface {
	cliLogoutRes()
}

type CreateEndpointRes interface {
	createEndpointRes()
}

type CreateFilterRes interface {
	createFilterRes()
}

type DeleteDomainRes interface {
	deleteDomainRes()
}

type DeleteEmailRes interface {
	deleteEmailRes()
}

type DeleteEndpointRes interface {
	deleteEndpointRes()
}

type DeleteFilterRes interface {
	deleteFilterRes()
}

type DiscardEmailContentRes interface {
	discardEmailContentRes()
}

type DownloadAttachmentsRes interface {
	downloadAttachmentsRes()
}

type DownloadRawEmailRes interface {
	downloadRawEmailRes()
}

type GetAccountRes interface {
	getAccountRes()
}

type GetEmailRes interface {
	getEmailRes()
}

type GetSendPermissionsRes interface {
	getSendPermissionsRes()
}

type GetSentEmailRes interface {
	getSentEmailRes()
}

type GetStorageStatsRes interface {
	getStorageStatsRes()
}

type GetWebhookSecretRes interface {
	getWebhookSecretRes()
}

type ListDeliveriesRes interface {
	listDeliveriesRes()
}

type ListDomainsRes interface {
	listDomainsRes()
}

type ListEmailsRes interface {
	listEmailsRes()
}

type ListEndpointsRes interface {
	listEndpointsRes()
}

type ListFiltersRes interface {
	listFiltersRes()
}

type ListSentEmailsRes interface {
	listSentEmailsRes()
}

type PollCliLoginRes interface {
	pollCliLoginRes()
}

type ReplayDeliveryRes interface {
	replayDeliveryRes()
}

type ReplayEmailWebhooksRes interface {
	replayEmailWebhooksRes()
}

type ReplyToEmailRes interface {
	replyToEmailRes()
}

type RotateWebhookSecretRes interface {
	rotateWebhookSecretRes()
}

type SearchEmailsRes interface {
	searchEmailsRes()
}

type SendEmailRes interface {
	sendEmailRes()
}

type StartCliLoginRes interface {
	startCliLoginRes()
}

type TestEndpointRes interface {
	testEndpointRes()
}

type UpdateAccountRes interface {
	updateAccountRes()
}

type UpdateDomainRes interface {
	updateDomainRes()
}

type UpdateEndpointRes interface {
	updateEndpointRes()
}

type UpdateFilterRes interface {
	updateFilterRes()
}

type VerifyDomainRes interface {
	verifyDomainRes()
}
