// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// AddDomain implements addDomain operation.
	//
	// Creates an unverified domain claim. You will receive a
	// `verification_token` to add as a DNS TXT record before
	// calling the verify endpoint.
	//
	// POST /domains
	AddDomain(ctx context.Context, req *AddDomainInput) (AddDomainRes, error)
	// CreateEndpoint implements createEndpoint operation.
	//
	// Creates a new webhook endpoint. If a deactivated endpoint with the
	// same URL and domain exists, it is reactivated instead.
	// Subject to plan limits on the number of active endpoints.
	//
	// POST /endpoints
	CreateEndpoint(ctx context.Context, req *CreateEndpointInput) (CreateEndpointRes, error)
	// CreateFilter implements createFilter operation.
	//
	// Creates a new whitelist or blocklist filter. Per-domain filters
	// require a Pro plan. Patterns are stored as lowercase.
	//
	// POST /filters
	CreateFilter(ctx context.Context, req *CreateFilterInput) (CreateFilterRes, error)
	// DeleteDomain implements deleteDomain operation.
	//
	// Deletes a verified or unverified domain claim.
	//
	// DELETE /domains/{id}
	DeleteDomain(ctx context.Context, params DeleteDomainParams) (DeleteDomainRes, error)
	// DeleteEmail implements deleteEmail operation.
	//
	// Delete an email.
	//
	// DELETE /emails/{id}
	DeleteEmail(ctx context.Context, params DeleteEmailParams) (DeleteEmailRes, error)
	// DeleteEndpoint implements deleteEndpoint operation.
	//
	// Soft-deletes a webhook endpoint. The endpoint will no longer
	// receive webhook deliveries.
	//
	// DELETE /endpoints/{id}
	DeleteEndpoint(ctx context.Context, params DeleteEndpointParams) (DeleteEndpointRes, error)
	// DeleteFilter implements deleteFilter operation.
	//
	// Delete a filter rule.
	//
	// DELETE /filters/{id}
	DeleteFilter(ctx context.Context, params DeleteFilterParams) (DeleteFilterRes, error)
	// DownloadAttachments implements downloadAttachments operation.
	//
	// Downloads all attachments as a gzip-compressed tar archive.
	// Authenticates via a signed download token (provided in webhook
	// payloads) or a valid session.
	//
	// GET /emails/{id}/attachments.tar.gz
	DownloadAttachments(ctx context.Context, params DownloadAttachmentsParams) (DownloadAttachmentsRes, error)
	// DownloadRawEmail implements downloadRawEmail operation.
	//
	// Downloads the raw RFC 822 email file (.eml). Authenticates via
	// a signed download token (provided in webhook payloads) or a
	// valid session.
	//
	// GET /emails/{id}/raw
	DownloadRawEmail(ctx context.Context, params DownloadRawEmailParams) (DownloadRawEmailRes, error)
	// GetAccount implements getAccount operation.
	//
	// Get account info.
	//
	// GET /account
	GetAccount(ctx context.Context) (GetAccountRes, error)
	// GetEmail implements getEmail operation.
	//
	// Get email details.
	//
	// GET /emails/{id}
	GetEmail(ctx context.Context, params GetEmailParams) (GetEmailRes, error)
	// GetStorageStats implements getStorageStats operation.
	//
	// Get storage usage.
	//
	// GET /account/storage
	GetStorageStats(ctx context.Context) (GetStorageStatsRes, error)
	// GetWebhookSecret implements getWebhookSecret operation.
	//
	// Returns the webhook signing secret for your account. If no secret
	// exists yet, one is generated automatically on first access.
	//
	// GET /account/webhook-secret
	GetWebhookSecret(ctx context.Context) (GetWebhookSecretRes, error)
	// ListDeliveries implements listDeliveries operation.
	//
	// Returns a paginated list of webhook delivery attempts. Each delivery
	// includes a nested `email` object with sender, recipient, and subject.
	//
	// GET /webhooks/deliveries
	ListDeliveries(ctx context.Context, params ListDeliveriesParams) (ListDeliveriesRes, error)
	// ListDomains implements listDomains operation.
	//
	// Returns all verified and unverified domains for your organization,
	// sorted by creation date (newest first). Each domain includes a
	// `verified` boolean to distinguish between the two states.
	//
	// GET /domains
	ListDomains(ctx context.Context) (ListDomainsRes, error)
	// ListEmails implements listEmails operation.
	//
	// Returns a paginated list of received emails. Supports filtering by
	// domain, status, date range, and free-text search across subject,
	// sender, and recipient fields.
	//
	// GET /emails
	ListEmails(ctx context.Context, params ListEmailsParams) (ListEmailsRes, error)
	// ListEndpoints implements listEndpoints operation.
	//
	// Returns all active (non-deleted) webhook endpoints.
	//
	// GET /endpoints
	ListEndpoints(ctx context.Context) (ListEndpointsRes, error)
	// ListFilters implements listFilters operation.
	//
	// Returns all whitelist and blocklist filter rules.
	//
	// GET /filters
	ListFilters(ctx context.Context) (ListFiltersRes, error)
	// ReplayDelivery implements replayDelivery operation.
	//
	// Re-sends the stored webhook payload from a previous delivery attempt.
	// If the original endpoint is still active, it is targeted. If the
	// original endpoint was deleted, the first active endpoint is used.
	// Deactivated endpoints cannot be replayed to.
	//
	// POST /webhooks/deliveries/{id}/replay
	ReplayDelivery(ctx context.Context, params ReplayDeliveryParams) (ReplayDeliveryRes, error)
	// ReplayEmailWebhooks implements replayEmailWebhooks operation.
	//
	// Re-delivers the webhook payload for this email to all active
	// endpoints matching the email's domain. Includes rate limiting
	// to prevent stampeding.
	//
	// POST /emails/{id}/replay
	ReplayEmailWebhooks(ctx context.Context, params ReplayEmailWebhooksParams) (ReplayEmailWebhooksRes, error)
	// RotateWebhookSecret implements rotateWebhookSecret operation.
	//
	// Generates a new webhook signing secret, replacing the current one.
	// Rate limited to once per 60 minutes.
	//
	// POST /account/webhook-secret/rotate
	RotateWebhookSecret(ctx context.Context) (RotateWebhookSecretRes, error)
	// TestEndpoint implements testEndpoint operation.
	//
	// Sends a sample `email.received` event to the endpoint. The request
	// includes SSRF protection (private IP rejection and DNS pinning).
	// Rate limited to 4 per minute and 30 per hour (non-exempt).
	// Successful deliveries and verified-domain endpoints are exempt
	// from the rate limit.
	//
	// POST /endpoints/{id}/test
	TestEndpoint(ctx context.Context, params TestEndpointParams) (TestEndpointRes, error)
	// UpdateAccount implements updateAccount operation.
	//
	// Update account settings.
	//
	// PATCH /account
	UpdateAccount(ctx context.Context, req *UpdateAccountInput) (UpdateAccountRes, error)
	// UpdateDomain implements updateDomain operation.
	//
	// Update a verified domain's settings. Only verified domains can be
	// updated. Per-domain spam thresholds require a Pro plan.
	//
	// PATCH /domains/{id}
	UpdateDomain(ctx context.Context, req *UpdateDomainInput, params UpdateDomainParams) (UpdateDomainRes, error)
	// UpdateEndpoint implements updateEndpoint operation.
	//
	// Updates an active webhook endpoint. If the URL is changed, the old
	// endpoint is deactivated and a new one is created (or an existing
	// deactivated endpoint with the new URL is reactivated).
	//
	// PATCH /endpoints/{id}
	UpdateEndpoint(ctx context.Context, req *UpdateEndpointInput, params UpdateEndpointParams) (UpdateEndpointRes, error)
	// UpdateFilter implements updateFilter operation.
	//
	// Toggle a filter's enabled state.
	//
	// PATCH /filters/{id}
	UpdateFilter(ctx context.Context, req *UpdateFilterInput, params UpdateFilterParams) (UpdateFilterRes, error)
	// VerifyDomain implements verifyDomain operation.
	//
	// Checks DNS records (MX and TXT) to verify domain ownership.
	// On success, the domain is promoted from unverified to verified.
	// On failure, returns which checks passed and which failed.
	//
	// POST /domains/{id}/verify
	VerifyDomain(ctx context.Context, params VerifyDomainParams) (VerifyDomainRes, error)
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h   Handler
	sec SecurityHandler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, sec SecurityHandler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		sec:        sec,
		baseServer: s,
	}, nil
}
