// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// AddDomain implements addDomain operation.
//
// Creates an unverified domain claim. You will receive a
// `verification_token` to add as a DNS TXT record before
// calling the verify endpoint.
//
// POST /domains
func (UnimplementedHandler) AddDomain(ctx context.Context, req *AddDomainInput) (r AddDomainRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateEndpoint implements createEndpoint operation.
//
// Creates a new webhook endpoint. If a deactivated endpoint with the
// same URL and domain exists, it is reactivated instead.
// Subject to plan limits on the number of active endpoints.
//
// POST /endpoints
func (UnimplementedHandler) CreateEndpoint(ctx context.Context, req *CreateEndpointInput) (r CreateEndpointRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateFilter implements createFilter operation.
//
// Creates a new whitelist or blocklist filter. Per-domain filters
// require a Pro plan. Patterns are stored as lowercase.
//
// POST /filters
func (UnimplementedHandler) CreateFilter(ctx context.Context, req *CreateFilterInput) (r CreateFilterRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteDomain implements deleteDomain operation.
//
// Deletes a verified or unverified domain claim.
//
// DELETE /domains/{id}
func (UnimplementedHandler) DeleteDomain(ctx context.Context, params DeleteDomainParams) (r DeleteDomainRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteEmail implements deleteEmail operation.
//
// Delete an email.
//
// DELETE /emails/{id}
func (UnimplementedHandler) DeleteEmail(ctx context.Context, params DeleteEmailParams) (r DeleteEmailRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteEndpoint implements deleteEndpoint operation.
//
// Soft-deletes a webhook endpoint. The endpoint will no longer
// receive webhook deliveries.
//
// DELETE /endpoints/{id}
func (UnimplementedHandler) DeleteEndpoint(ctx context.Context, params DeleteEndpointParams) (r DeleteEndpointRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteFilter implements deleteFilter operation.
//
// Delete a filter rule.
//
// DELETE /filters/{id}
func (UnimplementedHandler) DeleteFilter(ctx context.Context, params DeleteFilterParams) (r DeleteFilterRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DownloadAttachments implements downloadAttachments operation.
//
// Downloads all attachments as a gzip-compressed tar archive.
// Authenticates via a signed download token (provided in webhook
// payloads) or a valid session.
//
// GET /emails/{id}/attachments.tar.gz
func (UnimplementedHandler) DownloadAttachments(ctx context.Context, params DownloadAttachmentsParams) (r DownloadAttachmentsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DownloadRawEmail implements downloadRawEmail operation.
//
// Downloads the raw RFC 822 email file (.eml). Authenticates via
// a signed download token (provided in webhook payloads) or a
// valid session.
//
// GET /emails/{id}/raw
func (UnimplementedHandler) DownloadRawEmail(ctx context.Context, params DownloadRawEmailParams) (r DownloadRawEmailRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetAccount implements getAccount operation.
//
// Get account info.
//
// GET /account
func (UnimplementedHandler) GetAccount(ctx context.Context) (r GetAccountRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetEmail implements getEmail operation.
//
// Get email details.
//
// GET /emails/{id}
func (UnimplementedHandler) GetEmail(ctx context.Context, params GetEmailParams) (r GetEmailRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetStorageStats implements getStorageStats operation.
//
// Get storage usage.
//
// GET /account/storage
func (UnimplementedHandler) GetStorageStats(ctx context.Context) (r GetStorageStatsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetWebhookSecret implements getWebhookSecret operation.
//
// Returns the webhook signing secret for your account. If no secret
// exists yet, one is generated automatically on first access.
//
// GET /account/webhook-secret
func (UnimplementedHandler) GetWebhookSecret(ctx context.Context) (r GetWebhookSecretRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListDeliveries implements listDeliveries operation.
//
// Returns a paginated list of webhook delivery attempts. Each delivery
// includes a nested `email` object with sender, recipient, and subject.
//
// GET /webhooks/deliveries
func (UnimplementedHandler) ListDeliveries(ctx context.Context, params ListDeliveriesParams) (r ListDeliveriesRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListDomains implements listDomains operation.
//
// Returns all verified and unverified domains for your organization,
// sorted by creation date (newest first). Each domain includes a
// `verified` boolean to distinguish between the two states.
//
// GET /domains
func (UnimplementedHandler) ListDomains(ctx context.Context) (r ListDomainsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListEmails implements listEmails operation.
//
// Returns a paginated list of received emails. Supports filtering by
// domain, status, date range, and free-text search across subject,
// sender, and recipient fields.
//
// GET /emails
func (UnimplementedHandler) ListEmails(ctx context.Context, params ListEmailsParams) (r ListEmailsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListEndpoints implements listEndpoints operation.
//
// Returns all active (non-deleted) webhook endpoints.
//
// GET /endpoints
func (UnimplementedHandler) ListEndpoints(ctx context.Context) (r ListEndpointsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListFilters implements listFilters operation.
//
// Returns all whitelist and blocklist filter rules.
//
// GET /filters
func (UnimplementedHandler) ListFilters(ctx context.Context) (r ListFiltersRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ReplayDelivery implements replayDelivery operation.
//
// Re-sends the stored webhook payload from a previous delivery attempt.
// If the original endpoint is still active, it is targeted. If the
// original endpoint was deleted, the oldest active endpoint is used.
// Deactivated endpoints cannot be replayed to. Rate limited per-org,
// sharing an org-wide budget with email replays.
//
// POST /webhooks/deliveries/{id}/replay
func (UnimplementedHandler) ReplayDelivery(ctx context.Context, params ReplayDeliveryParams) (r ReplayDeliveryRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ReplayEmailWebhooks implements replayEmailWebhooks operation.
//
// Re-delivers the webhook payload for this email to all active
// endpoints matching the email's domain. Rate limited per-email
// (short cooldown between successive replays of the same email)
// and per-org (burst + sustained windows), sharing an org-wide
// budget with delivery replays.
//
// POST /emails/{id}/replay
func (UnimplementedHandler) ReplayEmailWebhooks(ctx context.Context, params ReplayEmailWebhooksParams) (r ReplayEmailWebhooksRes, _ error) {
	return r, ht.ErrNotImplemented
}

// RotateWebhookSecret implements rotateWebhookSecret operation.
//
// Generates a new webhook signing secret, replacing the current one.
// Rate limited to once per 60 minutes.
//
// POST /account/webhook-secret/rotate
func (UnimplementedHandler) RotateWebhookSecret(ctx context.Context) (r RotateWebhookSecretRes, _ error) {
	return r, ht.ErrNotImplemented
}

// TestEndpoint implements testEndpoint operation.
//
// Sends a sample `email.received` event to the endpoint. The request
// includes SSRF protection (private IP rejection and DNS pinning).
// Rate limited to 4 per minute and 30 per hour (non-exempt).
// Successful deliveries and verified-domain endpoints are exempt
// from the rate limit.
//
// POST /endpoints/{id}/test
func (UnimplementedHandler) TestEndpoint(ctx context.Context, params TestEndpointParams) (r TestEndpointRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateAccount implements updateAccount operation.
//
// Update account settings.
//
// PATCH /account
func (UnimplementedHandler) UpdateAccount(ctx context.Context, req *UpdateAccountInput) (r UpdateAccountRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateDomain implements updateDomain operation.
//
// Update a verified domain's settings. Only verified domains can be
// updated. Per-domain spam thresholds require a Pro plan.
//
// PATCH /domains/{id}
func (UnimplementedHandler) UpdateDomain(ctx context.Context, req *UpdateDomainInput, params UpdateDomainParams) (r UpdateDomainRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateEndpoint implements updateEndpoint operation.
//
// Updates an active webhook endpoint. If the URL is changed, the old
// endpoint is deactivated and a new one is created (or an existing
// deactivated endpoint with the new URL is reactivated).
//
// PATCH /endpoints/{id}
func (UnimplementedHandler) UpdateEndpoint(ctx context.Context, req *UpdateEndpointInput, params UpdateEndpointParams) (r UpdateEndpointRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateFilter implements updateFilter operation.
//
// Toggle a filter's enabled state.
//
// PATCH /filters/{id}
func (UnimplementedHandler) UpdateFilter(ctx context.Context, req *UpdateFilterInput, params UpdateFilterParams) (r UpdateFilterRes, _ error) {
	return r, ht.ErrNotImplemented
}

// VerifyDomain implements verifyDomain operation.
//
// Checks DNS records (MX and TXT) to verify domain ownership.
// On success, the domain is promoted from unverified to verified.
// On failure, returns which checks passed and which failed.
//
// POST /domains/{id}/verify
func (UnimplementedHandler) VerifyDomain(ctx context.Context, params VerifyDomainParams) (r VerifyDomainRes, _ error) {
	return r, ht.ErrNotImplemented
}
