// Code generated by ogen, DO NOT EDIT.

package api

// setDefaults set default value of fields.
func (s *CreateEndpointInput) setDefaults() {
	{
		val := bool(true)
		s.Enabled.SetTo(val)
	}
	{
		val := CreateEndpointInputKind("http")
		s.Kind.SetTo(val)
	}
	{
		val := bool(false)
		s.IsRouteTarget.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *SemanticSearchInput) setDefaults() {
	{
		val := SemanticSearchInputMode("hybrid")
		s.Mode.SetTo(val)
	}
	{
		val := int(10)
		s.Limit.SetTo(val)
	}
}
