"""x402 agent-to-agent payments.

``charge()`` to request a payment, ``pay()`` to settle one with a locally-held
key. Mirrors the Node SDK's ``x402`` module.
"""

from __future__ import annotations

from .client import (
    X402Challenge,
    X402Client,
    X402DeclinedPayment,
    X402EmailChallenge,
    X402EmailChallengeDetails,
    X402Error,
    X402PaymentRequirements,
    X402PayoutAddress,
    X402Receipt,
    X402SpendPolicy,
    create_x402_client,
    extract_email_challenge,
)
from .sign import (
    DEFAULT_MAX_WINDOW_SEC,
    DEFAULT_MIN_SETTLEMENT_HEADROOM_SEC,
    TRANSFER_WITH_AUTHORIZATION_TYPES,
    X402_INTERACTION_PROTOCOL,
    X402_INTERACTION_PROTOCOL_VERSION,
    BuiltPaymentStep,
    NonceBinding,
    PayoutRegistrationMessageInput,
    PrivateKeySigner,
    TokenDomain,
    TransferAuthorization,
    X402PaymentPayload,
    X402Signer,
    build_exact_evm_payment_payload,
    build_payment_step_envelope,
    build_payout_registration_message,
    compute_payment_validity_window,
    derive_eip3009_nonce,
    sign_interaction_payment,
    to_payment_payload,
    transfer_with_authorization_typed_data,
)

__all__ = [
    "DEFAULT_MAX_WINDOW_SEC",
    "DEFAULT_MIN_SETTLEMENT_HEADROOM_SEC",
    "TRANSFER_WITH_AUTHORIZATION_TYPES",
    "X402_INTERACTION_PROTOCOL",
    "X402_INTERACTION_PROTOCOL_VERSION",
    "BuiltPaymentStep",
    "NonceBinding",
    "PayoutRegistrationMessageInput",
    "PrivateKeySigner",
    "TokenDomain",
    "TransferAuthorization",
    "X402Challenge",
    "X402Client",
    "X402DeclinedPayment",
    "X402EmailChallenge",
    "X402EmailChallengeDetails",
    "X402Error",
    "X402PaymentPayload",
    "X402PaymentRequirements",
    "X402PayoutAddress",
    "X402Receipt",
    "X402Signer",
    "X402SpendPolicy",
    "build_exact_evm_payment_payload",
    "build_payment_step_envelope",
    "build_payout_registration_message",
    "compute_payment_validity_window",
    "create_x402_client",
    "derive_eip3009_nonce",
    "extract_email_challenge",
    "sign_interaction_payment",
    "to_payment_payload",
    "transfer_with_authorization_typed_data",
]
