from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT.parent / "json-schema" / "email-received-event.schema.json"
DEST = ROOT / "schema_generated.go"


def main() -> None:
    schema = json.loads(SOURCE.read_text())
    schema_json = json.dumps(schema, separators=(",", ":"), ensure_ascii=False)
    go_string_literal = json.dumps(schema_json)
    output = f'''package primitive

// Code generated by scripts/generate_schema_module.py. DO NOT EDIT.

var emailReceivedEventSchemaJSON = []byte({go_string_literal})
'''
    DEST.write_text(output)


if __name__ == "__main__":
    main()
