from enum import Enum

class ErrorResponseErrorCode(str, Enum):
    ACCESS_DENIED = "access_denied"
    AUTHORIZATION_PENDING = "authorization_pending"
    CANNOT_SEND_FROM_DOMAIN = "cannot_send_from_domain"
    CLERK_SIGNUP_FAILED = "clerk_signup_failed"
    CONFLICT = "conflict"
    DISCARD_NOT_ENABLED = "discard_not_enabled"
    EMAIL_DELIVERY_FAILED = "email_delivery_failed"
    EXPIRED_TOKEN = "expired_token"
    FORBIDDEN = "forbidden"
    INBOUND_NOT_REPLIABLE = "inbound_not_repliable"
    INTERNAL_ERROR = "internal_error"
    INVALID_DEVICE_CODE = "invalid_device_code"
    INVALID_SIGNUP_CODE = "invalid_signup_code"
    INVALID_SIGNUP_TOKEN = "invalid_signup_token"
    INVALID_VERIFICATION_CODE = "invalid_verification_code"
    MX_CONFLICT = "mx_conflict"
    NOT_FOUND = "not_found"
    NO_ORGS_FOR_USER = "no_orgs_for_user"
    ORG_NOT_ACCESSIBLE = "org_not_accessible"
    OUTBOUND_CAPACITY_EXHAUSTED = "outbound_capacity_exhausted"
    OUTBOUND_DISABLED = "outbound_disabled"
    OUTBOUND_KEY_INVALID = "outbound_key_invalid"
    OUTBOUND_KEY_MISSING = "outbound_key_missing"
    OUTBOUND_RELAY_FAILED = "outbound_relay_failed"
    OUTBOUND_RESPONSE_MALFORMED = "outbound_response_malformed"
    OUTBOUND_UNREACHABLE = "outbound_unreachable"
    RATE_LIMIT_EXCEEDED = "rate_limit_exceeded"
    RECIPIENT_NOT_ALLOWED = "recipient_not_allowed"
    SEARCH_TIMEOUT = "search_timeout"
    SLOW_DOWN = "slow_down"
    UNAUTHORIZED = "unauthorized"
    VALIDATION_ERROR = "validation_error"

    def __str__(self) -> str:
        return str(self.value)
