from enum import Enum

class ErrorResponseErrorCode(str, Enum):
    ACCESS_DENIED = "access_denied"
    ADDRESS_TAKEN = "address_taken"
    AUTHORIZATION_PENDING = "authorization_pending"
    CANNOT_SEND_FROM_DOMAIN = "cannot_send_from_domain"
    CHALLENGE_EXPIRED = "challenge_expired"
    CLERK_SIGNUP_FAILED = "clerk_signup_failed"
    CONFLICT = "conflict"
    DEVELOPER_USAGE_CREDIT_EXHAUSTED = "developer_usage_credit_exhausted"
    DISCARD_NOT_ENABLED = "discard_not_enabled"
    DOMAIN_CANNOT_SEND = "domain_cannot_send"
    EMAIL_DELIVERY_FAILED = "email_delivery_failed"
    EXPIRED_TOKEN = "expired_token"
    FEATURE_DISABLED = "feature_disabled"
    FORBIDDEN = "forbidden"
    INBOUND_NOT_REPLIABLE = "inbound_not_repliable"
    INTERNAL_ERROR = "internal_error"
    INVALID_DEVICE_CODE = "invalid_device_code"
    INVALID_SIGNUP_CODE = "invalid_signup_code"
    INVALID_SIGNUP_TOKEN = "invalid_signup_token"
    INVALID_VARIABLES = "invalid_variables"
    INVALID_VERIFICATION_CODE = "invalid_verification_code"
    MEMORY_CONFLICT = "memory_conflict"
    MISSING_SECRETS = "missing_secrets"
    MX_CONFLICT = "mx_conflict"
    NAME_EXHAUSTED = "name_exhausted"
    NOT_FOUND = "not_found"
    NO_INBOUND_DOMAIN = "no_inbound_domain"
    NO_ORGS_FOR_USER = "no_orgs_for_user"
    NO_PAYOUT_ADDRESS = "no_payout_address"
    ORG_NOT_ACCESSIBLE = "org_not_accessible"
    OUTBOUND_CAPACITY_EXHAUSTED = "outbound_capacity_exhausted"
    OUTBOUND_DISABLED = "outbound_disabled"
    OUTBOUND_KEY_INVALID = "outbound_key_invalid"
    OUTBOUND_KEY_MISSING = "outbound_key_missing"
    OUTBOUND_RELAY_FAILED = "outbound_relay_failed"
    OUTBOUND_RESPONSE_MALFORMED = "outbound_response_malformed"
    OUTBOUND_UNREACHABLE = "outbound_unreachable"
    OWNERSHIP_PROOF_FAILED = "ownership_proof_failed"
    PAYMENT_DECLINED = "payment_declined"
    PAYMENT_VERIFICATION_FAILED = "payment_verification_failed"
    RATE_LIMIT_EXCEEDED = "rate_limit_exceeded"
    RECIPIENT_NOT_ALLOWED = "recipient_not_allowed"
    ROUTE_CAP_REACHED = "route_cap_reached"
    SCAFFOLD_ONLY = "scaffold_only"
    SEARCH_TIMEOUT = "search_timeout"
    SETTLEMENT_FAILED = "settlement_failed"
    SLOW_DOWN = "slow_down"
    TEMPLATE_NOT_INSTALLABLE = "template_not_installable"
    UNAUTHORIZED = "unauthorized"
    UNKNOWN_SECRETS = "unknown_secrets"
    VALIDATION_ERROR = "validation_error"

    def __str__(self) -> str:
        return str(self.value)
